/**
 * Resource Mock Data
 * 카테고리별로 구조화된 리소스 데모 데이터
 */

import type { Resource } from '../model'

export const mockResources: Resource[] = [
  // TEMP_SENSORS (categoryId: 1) - 온도 센서군
  {
    internalId: 1,
    publicId: 'res-uuid-001',
    code: 'TEMP_001',
    categoryInternalId: 1,
    isActive: true,
    name: '엔진 온도계 #A01',
    description: '주요 생산 엔진 온도 모니터링',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'temperature', unit: 'celsius', precision: 0.1, range: { min: -20, max: 120 } },
      threshold: { warning: { min: 60, max: 80 }, critical: { min: 50, max: 90 } },
      mqtt: { topic: 'factory/line1/temp/001', qos: 1 },
    },
    metadata: { tags: ['critical', 'production'], priority: 'high', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    internalId: 2,
    publicId: 'res-uuid-002',
    code: 'TEMP_002',
    categoryInternalId: 1,
    isActive: true,
    name: '냉각수 온도계 #A02',
    description: '냉각 시스템 온도 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'temperature', unit: 'celsius', precision: 0.1, range: { min: 0, max: 100 } },
      threshold: { warning: { min: 40, max: 70 }, critical: { min: 30, max: 80 } },
      mqtt: { topic: 'factory/line1/temp/002', qos: 1 },
    },
    metadata: { tags: ['production', 'cooling'], priority: 'medium', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    internalId: 3,
    publicId: 'res-uuid-003',
    code: 'TEMP_003',
    categoryInternalId: 1,
    isActive: true,
    name: '배기가스 온도계 #A03',
    description: '배기 시스템 온도 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'temperature', unit: 'celsius', precision: 0.5, range: { min: 0, max: 500 } },
      mqtt: { topic: 'factory/line1/temp/003', qos: 1 },
    },
    metadata: { tags: ['exhaust', 'safety'], priority: 'high', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    internalId: 4,
    publicId: 'res-uuid-004',
    code: 'TEMP_004',
    categoryInternalId: 1,
    isActive: true,
    name: '엔진 온도계 #B01',
    description: '보조 생산 엔진 온도 모니터링',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'temperature', unit: 'celsius', precision: 0.1, range: { min: -20, max: 120 } },
      mqtt: { topic: 'factory/line1/temp/004', qos: 1 },
    },
    metadata: { tags: ['production'], priority: 'medium', location: { facility: '생산라인 B동' } },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-21'),
  },

  // PRESSURE_SENSORS (categoryId: 2) - 압력 센서군
  {
    internalId: 5,
    publicId: 'res-uuid-005',
    code: 'PRESS_001',
    categoryInternalId: 2,
    isActive: true,
    name: '유압 게이지 #P01',
    description: '주 유압 시스템 압력 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'pressure', unit: 'psi', precision: 1, range: { min: 0, max: 1000 } },
      threshold: { warning: { min: 50, max: 800 }, critical: { min: 30, max: 900 } },
      mqtt: { topic: 'factory/line1/pressure/001', qos: 1 },
    },
    metadata: { tags: ['critical', 'hydraulic'], priority: 'high', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    internalId: 6,
    publicId: 'res-uuid-006',
    code: 'PRESS_002',
    categoryInternalId: 2,
    isActive: true,
    name: '유압 게이지 #P02',
    description: '보조 유압 시스템 압력 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'pressure', unit: 'psi', range: { min: 0, max: 1000 } },
      mqtt: { topic: 'factory/line1/pressure/002', qos: 1 },
    },
    metadata: { tags: ['hydraulic'], priority: 'medium', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    internalId: 7,
    publicId: 'res-uuid-007',
    code: 'PRESS_003',
    categoryInternalId: 2,
    isActive: true,
    name: '공압 게이지 #P03',
    description: '공압 시스템 압력 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'pressure', unit: 'bar', range: { min: 0, max: 10 } },
      mqtt: { topic: 'factory/line1/pressure/003', qos: 1 },
    },
    metadata: { tags: ['pneumatic'], priority: 'medium', location: { facility: '생산라인 B동' } },
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-22'),
  },

  // VIBRATION_SENSORS (categoryId: 3) - 진동 센서군
  {
    internalId: 8,
    publicId: 'res-uuid-008',
    code: 'VIB_001',
    categoryInternalId: 3,
    isActive: true,
    name: '모터 진동계 #V01',
    description: '주 구동 모터 진동 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'vibration', unit: 'mm/s', precision: 0.01, range: { min: 0, max: 50 } },
      threshold: { warning: { max: 10 }, critical: { max: 20 } },
      mqtt: { topic: 'factory/line1/vibration/001', qos: 1 },
    },
    metadata: { tags: ['predictive', 'maintenance', 'critical'], priority: 'high', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    internalId: 9,
    publicId: 'res-uuid-009',
    code: 'VIB_002',
    categoryInternalId: 3,
    isActive: true,
    name: '베어링 진동계 #V02',
    description: '베어링 상태 진동 측정',
    attributes: {
      resourceType: 'sensor',
      sensor: { sensorType: 'vibration', unit: 'mm/s', precision: 0.01 },
      mqtt: { topic: 'factory/line1/vibration/002', qos: 1 },
    },
    metadata: { tags: ['bearing', 'maintenance'], priority: 'medium', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-24'),
  },

  // PRODUCTION_COUNTERS (categoryId: 4) - 생산량 카운터
  {
    internalId: 10,
    publicId: 'res-uuid-010',
    code: 'COUNT_001',
    categoryInternalId: 4,
    isActive: true,
    name: '제품 카운터 #C01',
    description: 'A라인 제품 생산 수량 집계',
    attributes: {
      resourceType: 'counter',
      counter: { unit: 'pieces', resetCycle: 'daily' },
      mqtt: { topic: 'factory/line1/counter/001', qos: 1 },
    },
    metadata: { tags: ['kpi', 'production', 'critical'], priority: 'high', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    internalId: 11,
    publicId: 'res-uuid-011',
    code: 'COUNT_002',
    categoryInternalId: 4,
    isActive: true,
    name: '불량품 카운터 #C02',
    description: 'A라인 불량품 수량 집계',
    attributes: {
      resourceType: 'counter',
      counter: { unit: 'pieces', resetCycle: 'daily' },
      mqtt: { topic: 'factory/line1/counter/002', qos: 1 },
    },
    metadata: { tags: ['quality', 'production'], priority: 'high', location: { facility: '생산라인 A동' } },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-26'),
  },

  // HVAC_EQUIPMENT (categoryId: 5) - HVAC 장비
  {
    internalId: 12,
    publicId: 'res-uuid-012',
    code: 'AC_101',
    categoryInternalId: 5,
    isActive: true,
    name: '1층 에어컨 #AC-101',
    description: '본관 1층 냉방 시스템',
    attributes: {
      resourceType: 'hvac',
      hvac: { type: 'air_conditioner', capacity: '10kW', zones: ['1F-East'] },
      control: { mode: 'auto', targetTemp: 22, currentTemp: 23 },
    },
    metadata: { tags: ['hvac', 'cooling'], priority: 'medium', location: { building: '본관', floor: '1층' } },
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-16'),
  },
  {
    internalId: 13,
    publicId: 'res-uuid-013',
    code: 'AC_102',
    categoryInternalId: 5,
    isActive: true,
    name: '1층 에어컨 #AC-102',
    description: '본관 1층 서측 냉방 시스템',
    attributes: {
      resourceType: 'hvac',
      hvac: { type: 'air_conditioner', capacity: '10kW', zones: ['1F-West'] },
      control: { mode: 'auto', targetTemp: 22 },
    },
    metadata: { tags: ['hvac', 'cooling'], priority: 'medium', location: { building: '본관', floor: '1층' } },
    createdAt: new Date('2024-01-09'),
    updatedAt: new Date('2024-01-17'),
  },
  {
    internalId: 14,
    publicId: 'res-uuid-014',
    code: 'FAN_201',
    categoryInternalId: 5,
    isActive: true,
    name: '2층 환기팬 #F-201',
    description: '본관 2층 환기 시스템',
    attributes: {
      resourceType: 'hvac',
      hvac: { type: 'ventilation_fan', capacity: '5kW' },
      control: { mode: 'schedule', schedule: '07:00-19:00' },
    },
    metadata: { tags: ['hvac', 'ventilation'], priority: 'low', location: { building: '본관', floor: '2층' } },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
  },

  // POWER_METERS (categoryId: 6) - 전력 계측기
  {
    internalId: 15,
    publicId: 'res-uuid-015',
    code: 'PWR_M101',
    categoryInternalId: 6,
    isActive: true,
    name: '1층 전력계 #M-101',
    description: '본관 1층 전력 사용량 측정',
    attributes: {
      resourceType: 'meter',
      meter: { type: 'power', unit: 'kWh', realtime: true },
      communication: { protocol: 'Modbus', address: '192.168.1.101' },
    },
    metadata: { tags: ['power', 'energy', 'realtime'], priority: 'high', location: { building: '본관', floor: '1층' } },
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-01-19'),
  },
  {
    internalId: 16,
    publicId: 'res-uuid-016',
    code: 'PWR_M201',
    categoryInternalId: 6,
    isActive: true,
    name: '2층 전력계 #M-201',
    description: '본관 2층 전력 사용량 측정',
    attributes: {
      resourceType: 'meter',
      meter: { type: 'power', unit: 'kWh', realtime: true },
      communication: { protocol: 'Modbus', address: '192.168.1.102' },
    },
    metadata: { tags: ['power', 'energy', 'realtime'], priority: 'high', location: { building: '본관', floor: '2층' } },
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-20'),
  },

  // LIGHTING_CONTROL (categoryId: 7) - 조명 제어 시스템
  {
    internalId: 17,
    publicId: 'res-uuid-017',
    code: 'LIGHT_Z101',
    categoryInternalId: 7,
    isActive: true,
    name: '1층 조명 존 #Z-101',
    description: '본관 1층 동측 조명 제어',
    attributes: {
      resourceType: 'lighting',
      lighting: { zoneId: 'Z-101', lightCount: 24, dimmable: true },
      control: { mode: 'auto', brightness: 80, schedule: true },
    },
    metadata: { tags: ['lighting', 'automation'], priority: 'low', location: { building: '본관', floor: '1층' } },
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-21'),
  },

  // SALES_TRANSACTIONS (categoryId: 8) - 판매 거래 데이터
  {
    internalId: 18,
    publicId: 'res-uuid-018',
    code: 'SALES_ONLINE',
    categoryInternalId: 8,
    isActive: true,
    name: '온라인 판매 트랜잭션',
    description: '온라인 쇼핑몰 실시간 판매 데이터',
    attributes: {
      resourceType: 'data_stream',
      stream: { type: 'transaction', channel: 'online', realtime: true },
      api: { endpoint: '/api/sales/online', method: 'GET' },
    },
    metadata: { tags: ['sales', 'online', 'revenue'], priority: 'high' },
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-21'),
  },
  {
    internalId: 19,
    publicId: 'res-uuid-019',
    code: 'SALES_POS',
    categoryInternalId: 8,
    isActive: true,
    name: 'POS 판매 트랜잭션',
    description: '매장 POS 실시간 판매 데이터',
    attributes: {
      resourceType: 'data_stream',
      stream: { type: 'transaction', channel: 'offline', realtime: true },
      api: { endpoint: '/api/sales/pos', method: 'GET' },
    },
    metadata: { tags: ['sales', 'pos', 'offline'], priority: 'high' },
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-22'),
  },

  // INVENTORY_DATA (categoryId: 9) - 재고 관리 데이터
  {
    internalId: 20,
    publicId: 'res-uuid-020',
    code: 'INV_WH01',
    categoryInternalId: 9,
    isActive: true,
    name: '물류센터 #1 재고',
    description: '물류센터 1번 실시간 재고 현황',
    attributes: {
      resourceType: 'data_stream',
      stream: { type: 'inventory', warehouse: 'WH-01', realtime: true },
      api: { endpoint: '/api/inventory/wh01', method: 'GET' },
    },
    metadata: { tags: ['inventory', 'warehouse', 'stock'], priority: 'high', location: { facility: '물류센터 #1' } },
    createdAt: new Date('2024-02-06'),
    updatedAt: new Date('2024-02-23'),
  },

  // CONVEYOR_SYSTEMS (categoryId: 10) - 컨베이어 시스템
  {
    internalId: 21,
    publicId: 'res-uuid-021',
    code: 'CONV_A01',
    categoryInternalId: 10,
    isActive: true,
    name: '컨베이어 벨트 #A01',
    description: 'A구역 주 컨베이어 라인',
    attributes: {
      resourceType: 'equipment',
      equipment: { type: 'conveyor', length: '50m', speed: '1.5m/s' },
      mqtt: { topic: 'warehouse/conveyor/a01', qos: 1 },
    },
    metadata: { tags: ['conveyor', 'automation'], priority: 'high', location: { facility: 'A동 물류창고' } },
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-02-07'),
  },
  {
    internalId: 22,
    publicId: 'res-uuid-022',
    code: 'CONV_B01',
    categoryInternalId: 10,
    isActive: true,
    name: '컨베이어 벨트 #B01',
    description: 'B구역 보조 컨베이어 라인',
    attributes: {
      resourceType: 'equipment',
      equipment: { type: 'conveyor', length: '30m', speed: '1.0m/s' },
      mqtt: { topic: 'warehouse/conveyor/b01', qos: 1 },
    },
    metadata: { tags: ['conveyor', 'automation'], priority: 'medium', location: { facility: 'A동 물류창고' } },
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-08'),
  },

  // BARCODE_SCANNERS (categoryId: 11) - 바코드 스캐너
  {
    internalId: 23,
    publicId: 'res-uuid-023',
    code: 'SCAN_001',
    categoryInternalId: 11,
    isActive: true,
    name: '바코드 스캐너 #S-001',
    description: '입고 구역 스캐너',
    attributes: {
      resourceType: 'scanner',
      scanner: { type: '2D_barcode', scanRate: '100/min' },
      mqtt: { topic: 'warehouse/scanner/001', qos: 1 },
    },
    metadata: { tags: ['barcode', 'tracking'], priority: 'high', location: { facility: 'A동 물류창고', room: '입고구역' } },
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-02-09'),
  },

  // INSPECTION_EQUIPMENT (categoryId: 12) - 검사 장비
  {
    internalId: 24,
    publicId: 'res-uuid-024',
    code: 'INSP_VIS_01',
    categoryInternalId: 12,
    isActive: true,
    name: '외관 검사 장비 #I-V01',
    description: 'AI 기반 외관 결함 검사',
    attributes: {
      resourceType: 'inspection',
      inspection: { type: 'visual', method: 'AI_vision', accuracy: 99.5 },
      communication: { protocol: 'REST', endpoint: 'http://qc.example.com/api/visual' },
    },
    metadata: { tags: ['inspection', 'visual', 'ai'], priority: 'high', location: { room: '품질관리실' } },
    createdAt: new Date('2024-02-17'),
    updatedAt: new Date('2024-02-26'),
  },
  {
    internalId: 25,
    publicId: 'res-uuid-025',
    code: 'INSP_DIM_01',
    categoryInternalId: 12,
    isActive: true,
    name: '치수 검사 장비 #I-D01',
    description: '3D 레이저 치수 측정',
    attributes: {
      resourceType: 'inspection',
      inspection: { type: 'dimension', method: '3D_laser', precision: 0.01 },
      communication: { protocol: 'REST', endpoint: 'http://qc.example.com/api/dimension' },
    },
    metadata: { tags: ['inspection', 'dimension', 'precision'], priority: 'high', location: { room: '품질관리실' } },
    createdAt: new Date('2024-02-18'),
    updatedAt: new Date('2024-02-27'),
  },
]
