/**
 * Data Source Mock Data
 */

import type { DataSource } from '../model'

export const mockDataSources: DataSource[] = [
  {
    internalId: 1,
    publicId: 'ds-uuid-001',
    code: 'FACTORY_LINE_1',
    userId: 'user-001',
    isActive: true,
    name: '1번 생산라인',
    attributes: {
      protocol: 'MQTT',
      host: 'mqtt.factory.example.com',
      port: 1883,
      timeout: 5000,
      retryCount: 3,
      authType: 'basic',
    },
    metadata: {
      organization: {
        department: 'Manufacturing',
        manager: '김철수',
        contact: 'kim@example.com',
      },
      tags: ['production', 'critical', 'mqtt'],
      documentationUrl: 'https://wiki.example.com/factory-line-1',
      inspectionStatus: 'approved',
      description: '스마트 팩토리 1번 생산라인의 실시간 센서 데이터 수집',
    },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    internalId: 2,
    publicId: 'ds-uuid-002',
    code: 'BUILDING_MAIN',
    userId: 'user-001',
    isActive: true,
    name: '본관 건물',
    attributes: {
      protocol: 'HTTP',
      host: 'building.example.com',
      port: 80,
      timeout: 3000,
      retryCount: 2,
      authType: 'none',
    },
    metadata: {
      organization: {
        department: 'Facilities',
        manager: '이영희',
        contact: 'lee@example.com',
      },
      tags: ['building', 'hvac', 'energy'],
      documentationUrl: 'https://wiki.example.com/building-main',
      inspectionStatus: 'approved',
      description: '본관 건물 HVAC 및 전력 관리 시스템',
    },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    internalId: 3,
    publicId: 'ds-uuid-003',
    code: 'SALES_SYSTEM',
    userId: 'user-002',
    isActive: true,
    name: '판매 데이터 시스템',
    attributes: {
      protocol: 'HTTPS',
      host: 'api.sales.example.com',
      port: 443,
      timeout: 10000,
      authType: 'bearer',
    },
    metadata: {
      organization: {
        department: 'Sales',
        manager: '박민수',
        contact: 'park@example.com',
      },
      tags: ['sales', 'api', 'revenue'],
      contract: {
        vendor: 'SalesForce Inc.',
        contractNumber: 'SF-2024-001',
        expiryDate: '2025-12-31',
      },
      inspectionStatus: 'approved',
      description: '실시간 판매 데이터 및 재고 관리 시스템',
    },
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    internalId: 4,
    publicId: 'ds-uuid-004',
    code: 'WAREHOUSE_A',
    userId: 'user-001',
    isActive: true,
    name: 'A동 물류창고',
    attributes: {
      protocol: 'MQTT',
      host: 'mqtt.warehouse.example.com',
      port: 1883,
      timeout: 5000,
      retryCount: 3,
      authType: 'api_key',
    },
    metadata: {
      organization: {
        department: 'Logistics',
        manager: '최영수',
        contact: 'choi@example.com',
      },
      tags: ['warehouse', 'logistics', 'inventory'],
      inspectionStatus: 'approved',
      description: 'A동 물류창고 자동화 설비 및 재고 추적',
    },
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    internalId: 5,
    publicId: 'ds-uuid-005',
    code: 'QUALITY_CONTROL',
    userId: 'user-003',
    isActive: true,
    name: '품질관리 시스템',
    attributes: {
      protocol: 'HTTPS',
      host: 'qc.example.com',
      port: 443,
      timeout: 8000,
      authType: 'oauth2',
    },
    metadata: {
      organization: {
        department: 'Quality Assurance',
        manager: '정민지',
        contact: 'jung@example.com',
      },
      tags: ['quality', 'inspection', 'compliance'],
      inspectionStatus: 'pending',
      description: '제품 품질 검사 및 불량률 분석 시스템',
    },
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    internalId: 6,
    publicId: 'ds-uuid-006',
    code: 'ENERGY_MONITOR',
    userId: 'user-001',
    isActive: false,
    name: '통합 에너지 모니터링',
    attributes: {
      protocol: 'WebSocket',
      host: 'ws.energy.example.com',
      port: 8080,
      timeout: 15000,
      authType: 'bearer',
    },
    metadata: {
      organization: {
        department: 'Facilities',
        manager: '이영희',
        contact: 'lee@example.com',
      },
      tags: ['energy', 'monitoring', 'realtime'],
      inspectionStatus: 'rejected',
      description: '전사 에너지 사용량 실시간 모니터링 (점검중)',
    },
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-02-28'),
  },
]
