/**
 * Category Mock Data
 */

import type { Category } from '../model'

export const mockCategories: Category[] = [
  // FACTORY_LINE_1 (id: 1) 카테고리
  {
    internalId: 1,
    publicId: 'cat-uuid-001',
    code: 'TEMP_SENSORS',
    dataSourceInternalId: 1,
    isActive: true,
    name: '온도 센서군',
    description: '생산라인 온도 측정 센서 - 엔진, 냉각수, 배기가스',
    attributes: { sensorCount: 8, calibrationCycle: '3months' },
    metadata: { tags: ['temperature', 'sensor', 'critical'], priority: 'high' },
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    internalId: 2,
    publicId: 'cat-uuid-002',
    code: 'PRESSURE_SENSORS',
    dataSourceInternalId: 1,
    isActive: true,
    name: '압력 센서군',
    description: '유압 시스템 압력 측정 센서',
    attributes: { sensorCount: 5, calibrationCycle: '6months' },
    metadata: { tags: ['pressure', 'sensor', 'hydraulic'], priority: 'high' },
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    internalId: 3,
    publicId: 'cat-uuid-003',
    code: 'VIBRATION_SENSORS',
    dataSourceInternalId: 1,
    isActive: true,
    name: '진동 센서군',
    description: '모터 및 기계 진동 모니터링',
    attributes: { sensorCount: 12, calibrationCycle: '12months' },
    metadata: { tags: ['vibration', 'predictive', 'maintenance'], priority: 'medium' },
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-18'),
  },
  {
    internalId: 4,
    publicId: 'cat-uuid-004',
    code: 'PRODUCTION_COUNTERS',
    dataSourceInternalId: 1,
    isActive: true,
    name: '생산량 카운터',
    description: '제품 생산 수량 집계',
    attributes: { counterCount: 4 },
    metadata: { tags: ['production', 'counter', 'kpi'] },
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-20'),
  },

  // BUILDING_MAIN (id: 2) 카테고리
  {
    internalId: 5,
    publicId: 'cat-uuid-005',
    code: 'HVAC_EQUIPMENT',
    dataSourceInternalId: 2,
    isActive: true,
    name: 'HVAC 장비',
    description: '냉난방 공조 장비 (에어컨, 히터, 환기 시스템)',
    attributes: { equipmentCount: 24, zones: ['1F', '2F', '3F', '4F'] },
    metadata: { tags: ['hvac', 'building', 'comfort'], priority: 'medium' },
    createdAt: new Date('2024-01-06'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    internalId: 6,
    publicId: 'cat-uuid-006',
    code: 'POWER_METERS',
    dataSourceInternalId: 2,
    isActive: true,
    name: '전력 계측기',
    description: '건물 전력 사용량 측정 및 모니터링',
    attributes: { meterCount: 16, realtime: true },
    metadata: { tags: ['power', 'meter', 'energy'], priority: 'high' },
    createdAt: new Date('2024-01-07'),
    updatedAt: new Date('2024-01-14'),
  },
  {
    internalId: 7,
    publicId: 'cat-uuid-007',
    code: 'LIGHTING_CONTROL',
    dataSourceInternalId: 2,
    isActive: true,
    name: '조명 제어 시스템',
    description: '스마트 조명 자동 제어',
    attributes: { zones: 32, automation: true },
    metadata: { tags: ['lighting', 'automation', 'energy-saving'] },
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-16'),
  },

  // SALES_SYSTEM (id: 3) 카테고리
  {
    internalId: 8,
    publicId: 'cat-uuid-008',
    code: 'SALES_TRANSACTIONS',
    dataSourceInternalId: 3,
    isActive: true,
    name: '판매 거래 데이터',
    description: '실시간 판매 트랜잭션 정보',
    attributes: { channels: ['online', 'offline', 'mobile'] },
    metadata: { tags: ['sales', 'transaction', 'revenue'] },
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-18'),
  },
  {
    internalId: 9,
    publicId: 'cat-uuid-009',
    code: 'INVENTORY_DATA',
    dataSourceInternalId: 3,
    isActive: true,
    name: '재고 관리 데이터',
    description: '실시간 재고 수량 및 입출고 이력',
    attributes: { warehouses: 5, skuCount: 1250 },
    metadata: { tags: ['inventory', 'stock', 'warehouse'] },
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-19'),
  },

  // WAREHOUSE_A (id: 4) 카테고리
  {
    internalId: 10,
    publicId: 'cat-uuid-010',
    code: 'CONVEYOR_SYSTEMS',
    dataSourceInternalId: 4,
    isActive: true,
    name: '컨베이어 시스템',
    description: '자동 이송 컨베이어 설비',
    attributes: { conveyorCount: 8, totalLength: '500m' },
    metadata: { tags: ['conveyor', 'automation', 'logistics'] },
    createdAt: new Date('2024-01-11'),
    updatedAt: new Date('2024-02-06'),
  },
  {
    internalId: 11,
    publicId: 'cat-uuid-011',
    code: 'BARCODE_SCANNERS',
    dataSourceInternalId: 4,
    isActive: true,
    name: '바코드 스캐너',
    description: '제품 식별 및 추적용 스캐너',
    attributes: { scannerCount: 32, scanRate: '1000/hour' },
    metadata: { tags: ['barcode', 'tracking', 'identification'] },
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-02-04'),
  },

  // QUALITY_CONTROL (id: 5) 카테고리
  {
    internalId: 12,
    publicId: 'cat-uuid-012',
    code: 'INSPECTION_EQUIPMENT',
    dataSourceInternalId: 5,
    isActive: true,
    name: '검사 장비',
    description: '제품 품질 검사 자동화 장비',
    attributes: { equipmentCount: 6, inspectionTypes: ['visual', 'dimension', 'weight'] },
    metadata: { tags: ['inspection', 'quality', 'automation'] },
    createdAt: new Date('2024-02-16'),
    updatedAt: new Date('2024-02-24'),
  },
]
